import { editor } from "monaco-editor";

const mocha = {
  base: "#1e1e2e",
  mantle: "#181825",
  surface: "#313244",
  overlay: "#6c7086",
  text: "#cdd6f4",
  lavender: "#b4befe",
  blue: "#89b4fa",
  sapphire: "#74c7ec",
  sky: "#89dceb",
  teal: "#94e2d5",
  green: "#a6e3a1",
  yellow: "#f9e2af",
  peach: "#fab387",
  red: "#f38ba8",
  pink: "#f5c2e7",
  mauve: "#cba6f7",
};

export const themeCatpuccinMocha: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: false,
  colors: {
    "editor.background": mocha.base,
    "editor.foreground": mocha.text,
    "editor.lineHighlightBackground": mocha.mantle,
    "editor.selectionBackground": mocha.surface + "99",
    "editorCursor.foreground": mocha.lavender,
    "editorLineNumber.foreground": mocha.overlay,
    "editorLineNumber.activeForeground": mocha.lavender,
    "editor.findMatchBackground": mocha.peach + "44",
    "editorBracketMatch.background": mocha.surface,
    "editorBracketMatch.border": mocha.lavender,
    "editorWidget.background": mocha.mantle,
    "editorSuggestWidget.background": mocha.mantle,
    "editorSuggestWidget.selectedBackground": mocha.surface,
    "editorSuggestWidget.border": mocha.surface,
    "scrollbarSlider.background": mocha.surface + "88",
    "scrollbarSlider.hoverBackground": mocha.overlay + "88",
    "minimap.background": mocha.mantle,
  },
  rules: [
    { token: "*", fontStyle: "bold" },
    { token: "comment", foreground: mocha.overlay, fontStyle: "italic bold" },
    { token: "keyword", foreground: mocha.mauve },
    { token: "string", foreground: mocha.green },
    { token: "number", foreground: mocha.peach },
    { token: "type", foreground: mocha.yellow },
    { token: "class", foreground: mocha.yellow },
    { token: "function", foreground: mocha.blue },
    { token: "variable", foreground: mocha.text },
    { token: "parameter", foreground: mocha.peach, fontStyle: "italic" },
    { token: "operator", foreground: mocha.sky },
    { token: "delimiter", foreground: mocha.overlay },
    { token: "tag", foreground: mocha.mauve },
    { token: "attribute.name", foreground: mocha.blue },
    { token: "attribute.value", foreground: mocha.green },
  ],
};
